language: nix
script: "./travis/build.sh"
after_success: "./travis/trigger-downstream.sh"
cache:
  timeout: 86400
  directories:
  - "${HOME}/.m2"
branches:
  only:
  - master
env:
  global:
  - secure: OnIEo82j4k/TwxSrU1Am8BwDPxQkdF5eBiD52cnqIDQUqMY6NVgJFKkQn8fPlb1OD97IBaspS8fAG+wAAa99eBendNjqpJR0wHnNbO4/CIvqSyKruhHUq0/oGdUbbDpGeXkGvIEUlGF267IKmUuk9Wv1PR2H6pLth1qgGwrk5HTc97dGkksTTVzuEHrougnLLVg4lOxx3cocMWiZ3HRz0EMYw7vo97vTi22wOAoFork5oAPT5tkLrhmpYOYQ+n7B1sOBfZH8q+q6+fkG3HTYUdYjjRAsESvyac7AfsQ1uI5+sqhcbfy1gsCHx6NjtljAR7OxgLc3zqizLS0jztZxlMG+OYTh5iwCMyCZfAfH5GuqBzm7sZIV0R/RKo4W727OsMdt4wJQj9m5zDceAg7VcSRP+4x/IJ+hXsYTSA0NKcaVihXTii0I4mjrRzjBPmqDPZLGD5mmupEXK9K37PkZsQAJqnUwq5vvI6ANaWGyzSc4ahUdKrKZZWH1S3xQeQo7i4denddixjG/XOyfb3zU7ostrbegVZEZdz84fjT5Sene2kOzbeMTI9aNugfDbNhUgPXXZm7XcZVxf/1fOlnDGcineEJvIt2SgGTo3vhraKadzxG3m8jd5oq3EUUri/2xbj9ZOMsDkNXqjr/f1dl2KkR+tvpMY+9w0mXDXPD8+w4=
  - secure: cuRLaEXgXLQpH4zZtGpqOgPRDsTChyw89Fg3OE+ed63SMgq1L4oVaiCgeM6f1Sovv7IlRgyzJSyE2HYc+AHp1Hofah3xzaAp1OmH1fcsNrXKIm8/YhjGNx5uZMsi3bxn2kyLoBlm8QumZhiBe7VLlwLHwo4ekPkLj08yEYY+u6BUqq7MrMupK0KtU8LZkB0dO6m9Tr28MUSFsesAbqbzoUv9jKwNb+J6ZQwKGKpLw6dRh/Kg076tnZgXZzT6OmyS0+bLmjPj3cl71ECXOfjk8gzp4yc1hBzGWKhYCKdbiYsS6YqSatS/p9JIOULrIK52Cw7gOjTCwfYn2oIY002Gc3ZCDFlpkzz2pUcj6jjA8SNrgn5evQhcnxxT1143cBrvVRN1IuyhrOMCwwwe/AD/qxW4s8qL7iL0DEJe4lHrooo91Ggtoj48JvSpvAkbDV6UMK+lLT8mDHUwN6oOTu/MYV9+lanryuBGDSMR700O32sg/3KPTubANJafh2gwVBv/1Iz/Hrwg2dRrEBM5ksZbXBLwrzE1294g78//J/mnCZx0Ms7I93Ck9YrlXIc7m3aFW8+/MWwSsDq0BtQw2RbEilxvUaevmKvXG9duBilrJ84h1QX9aqCYsdrXWkmqnRKNmbqvVUbxZCeb+3QTaUbPCjkIHdakWDtvZwaiTgu2s3A=
