language: nix
script: "./travis/build.sh"
after_success: "./travis/trigger-downstream.sh"
cache:
  timeout: 86400
  directories:
  - "${HOME}/.m2"
branches:
  only:
  - master
env:
  global:
  - AWS_DEFAULT_REGION: ap-southeast-2
  # TRAVIS_TOKEN
  - secure: iCoVd2tkhMWI9ylvyQtmOIDdhgGr0ydi44+nJ/p5KUPCxLhX+iyvOQvfefrp+bwXpYCtQTYNwCFz9dWnKD9VgTkIq0RLXIgAbOPrQBYmg39cSCEcoDN/kH9+A2YuEoaofQJ0ZvRt+3RfhDE9bGGRyuEp7KX7mJF7AdSFG+XCmy2NXj6JRH1/w3+DGaXjmpdKUVmpj0++X/cGsqSFu8007qZqqBrHJS1W+xIVNkEzD3COL44lusU5g8WhqHeHItH5u0oV0VvXuO9wbRhnRkoeIrAqYVjw4imWlXzyWfkUd7jdSx/suLrLfVB/FvIFt5ZHIppayu4P72OV+szTpD45M2IAIAociVI0Sagz28uTePUXmIe7N8xgQKww7K7gitb2P8ESVIBt0phWxVNENgmFbPlTS0mz300SpyPAA7ZfX94Lc2WT3jlEUni/Qec/UZZkKhE9HgU4bV+nYW7KYQnBzrE9hF+qWo8P39rcSpN+tqdwiuR6CUPDTpcx5nnKFFeVWmDoFglCsQ2sGUiqUolxtTZ4xyrfMiHB3My2hS26I/jG2laND0A6WTDMsn8aK3EnRQI/KVpg34wPgYt1px9sQN6QHGEL5lt6Im5zRefk7rNaC3j9x4C48Ocv0EOwA1nrtimdDZnJpeuYleN/A/e3WlNB+nG0AoAbFtseyfsUulg=
  - AWS_ACCESS_KEY_ID: AKIA2AV2YTL6QKCM4I5F
    # AWS_SECRET_ACCESS_KEY, /geodesy-operations/iam-user/bitbucket-pipelines/access-key/AKIA2AV2YTL6QKCM4I5F/secret-access-key
  - secure: VmtYoeP0KuXq5RI8i0x0e6Pw149ii/0D5Qzqpvel9bHB8zNrmjiHRdCPNKMTJ7KiQ255L81K4+E6TEF0176jOve5ZdMtk8T/TpfL8YiGKgA2Sik61PAKkUQh2+2iU2xNHCXdLTt+ExrGFpLnwjC2KXjC+5x9rAcT0X4PwTiQLF7iSpUzLIjskziR5UXKshI1fR8oonNJNsDyJCA2KC3/rm2JzSWUWichSqMClR4RO4Yw/gO66mGYLSn2YwYNEjIw7w1OW5jJbwyUaQVPr5cwCVNhXozRrbMSpePib3gy1gz0i0va1+IfLR8sf8Vl/+EQW3QdXtlUNdUviW3wrC41qvbSXBWq1g8Z6m4v69hYsf7MJ18iqrCkWuq53oTWcHfWXdpr/sxApLyNK4kxx90+sHVz7tbc1VIdvlUN5l+K1jqFRu8oJofGExzwt4o6Ne2A2zN6UDt/3D1Gd3vBsE0g0sF9dQ78OcGsFEr/geM4YfEQ1ImSvj0s0SOSehhbgz/gVWm+fFh5tBbkP3ShT7Os9SA/zD8JG2nL0dXeHfoObJ5upV80hezYM51xUcmP1pNjxkCEol9XRyyxccOtmsZGCB65kCuhayyT70ghqpkgciZPDJyfpm4C4IewVY8SUdtjUo19n29LnHzFLkGOBlAXuSnR4P+1GRBu5X4xEhQUr8Y=
