language: nix
script: "./travis/build.sh"
after_success: "./travis/trigger-downstream.sh"
cache:
  timeout: 86400
  directories:
  - "${HOME}/.m2"
branches:
  only:
  - master
env:
  global:
  - AWS_DEFAULT_REGION: ap-southeast-2
  # TRAVIS_TOKEN
  - secure: iCoVd2tkhMWI9ylvyQtmOIDdhgGr0ydi44+nJ/p5KUPCxLhX+iyvOQvfefrp+bwXpYCtQTYNwCFz9dWnKD9VgTkIq0RLXIgAbOPrQBYmg39cSCEcoDN/kH9+A2YuEoaofQJ0ZvRt+3RfhDE9bGGRyuEp7KX7mJF7AdSFG+XCmy2NXj6JRH1/w3+DGaXjmpdKUVmpj0++X/cGsqSFu8007qZqqBrHJS1W+xIVNkEzD3COL44lusU5g8WhqHeHItH5u0oV0VvXuO9wbRhnRkoeIrAqYVjw4imWlXzyWfkUd7jdSx/suLrLfVB/FvIFt5ZHIppayu4P72OV+szTpD45M2IAIAociVI0Sagz28uTePUXmIe7N8xgQKww7K7gitb2P8ESVIBt0phWxVNENgmFbPlTS0mz300SpyPAA7ZfX94Lc2WT3jlEUni/Qec/UZZkKhE9HgU4bV+nYW7KYQnBzrE9hF+qWo8P39rcSpN+tqdwiuR6CUPDTpcx5nnKFFeVWmDoFglCsQ2sGUiqUolxtTZ4xyrfMiHB3My2hS26I/jG2laND0A6WTDMsn8aK3EnRQI/KVpg34wPgYt1px9sQN6QHGEL5lt6Im5zRefk7rNaC3j9x4C48Ocv0EOwA1nrtimdDZnJpeuYleN/A/e3WlNB+nG0AoAbFtseyfsUulg=
  - AWS_ACCESS_KEY_ID: AKIA2AV2YTL6SUSQP56W
  # AWS_SECRET_ACCESS_KEY, /geodesy-operations/iam-user/travis-ci/access-key/AKIA2AV2YTL6SUSQP56W/secret-access-key
  - secure: Q1w3jq26hrORprBWfcke2+Be8Nkc4ldQEoUVYnxeNO1Zt+8xQ7dWo+F9g1E6EFkdsT7GHkD9fMEJCp1tkoZVnntgHaj4jczvplo9Hb8U/C1/blnCOn+okDdNl6e9Tay7+HVI+jYXLf5mly0CutRp0ObDwuuDlog1307iRD5sWOcTNozvSnwhsqOk1SLO65UAOyaHRnZ8zjsQxm+zQoOLmH7Ox3WurTfJVG/eBKeWmOjZB8lKAB/GAIBIYuwXPoUCu5xJO8HJovtVQ3z48kF5+ZKZz69Y24GK28Fh1mn+jAK2rlsMfH+eAwT6CE16KQLA8DD+wYEBBugL8UDVcGyeUAt+eV45C018QMcK5wWIcdrvvKHVPU2fkTndRyT7lfuOs+d5ZAIDdZmhC32fSYEit6EgOfntJYCVYxcqMcbo51jHnNGskFV5Q5UkTQXwKEL56APP4ivHSh4wFecOUTLI9BJqIDn8dnzwHJLi6hzH7Iu+oW3UyTnnHr3n0J4P+GYpGnDpYpzSNTRPWgMaDPK25qdqYlJI1q+gh81sqjfQUCzxLNBI6wiqZrPeE7oDZMLsRwPP8VkfEnAoRLWeC8p4t6/5X8Zhaz5+HKTcGnro/zroCgQSnRLJcAs39Qo52YNgqP67kdHSm/9vd6YL+EcJZ3KwJ6jV7f08iOf7Hs9OEl4=
